Feature/issue#12 - Spotify 소셜 로그인 구현
petit-a-petit/MIML pull request #28
Opened 2023-10-11 16:04 UTC by minju412

### ✍️ Description
- OAuth 2.0 을 사용해 소셜 로그인을 구현하였으며, Provider는 Spotify 입니다.

<br>

### 🎯 Key Changes
- `.oauth.api.LoginController`: 스포티파이 로그인 페이지로 리다이렉트합니다.
- `oauth.handler.CustomOAuth2AuthenticationSuccessHandler`: 스포티파이 로그인 성공 시, 스포티파이로부터 제공받은 엑세스 토큰을 쿼리 파라미터에 담아 로그인 성공 페이지로 리다이렉트합니다.
- `oauth.handler.OAuth2AuthenticationFailureHandler`: 로그인 실패 시 로그를 남기고 Exception을 발생시킵니다.
- `oauth.provider.OAuth2Provider`: Provider의 종류와 정보를 나타내는 Enum으로 현재는 `SPOTIFY`만 포함되어 있습니다.
- `oauth.provider.OAuth2UserInfo`: OAuth2User 정보를 나타내는 클래스입니다.
- `oauth.provider.SpotifyUserInfo`: Spotify 사용자 정보를 나타내는 클래스입니다.
- `oauth.CustomOAuth2User`: `DefaultOAuth2User`를 상속한 클래스로 Provider와 엑세스 토큰을 가지고 있습니다.
- `oauth.CustomOAuth2UserService`: `code`를 통해 사용자 정보를 로드하고 데이터베이스에 저장합니다.

<br>

### 💬 To Reviewers
- 주석 처리한 클래스는 JWT 관련 클래스로 현재 사용하지 않고 있으니 무시하셔도 좋습니다!
- 이전 회의 때 우리 앱 고유의 엑세스 토큰을 발급할 필요는 없다는 의견이 나왔는데요, [해당 디스커션](https://github.com/petit-a-petit/MIML/discussions/25)에서 우재님의 의견을 듣고 "정말 우리 앱에서 JWT를 발급할 필요가 없을까?"라는 고민을 하게 되었습니다.
    - 그 이유는, `친구 신청`과 같이 스포티파이 API를 사용하지 않고 우리 앱만의 서비스를 이용해야 하는 경우가 있기 때문입니다.
    - 관련해서 의견 주시면 감사하겠습니다! 🙇‍♀️

2023-10-18 07:10 UTC, kdmstj requested changes

2023-10-18 07:10 UTC, kdmstj commented on build.gradle
gson 라이브러리가 중복으로 추가 되었습니다.
```
implementation 'com.google.code.gson:gson'
```

2023-10-18 07:10 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/auth/oauth/CustomOauth2UserService.java
1. isFirst 변수로 최초 로그인 여부를 구분한 이유가 있을까요? Optional을 통해 최초 로그인 여부를 확인할 수 있다고 생각되는데 변수를 설정하신 이유가 궁금합니다!

2. 더불어 이미 로그인한 적이 있는 유저에 대한 정보를 다시 DB에 저장한 이유에 대해 궁금합니다.

3. processOAuth2User 메소드에 여러개의 로직(Oauth2 서비스 제공자 구분, 새로운 사용자 DB 저장, OAuth2 User 생성)이 포함되어있다고 생각되는데 분리하는 것은 어떨까요?

2023-10-18 07:10 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/auth/oauth/api/LoginController.java
1. @RestController 어노테이션을 작성하신 이유가 궁금합니다
해당 어노테이션은 @Controller에 @ResponseBody가 추가된 것으로 주 용도로는 JSON 형태로 객체 데이터를 반환하는 것으로 알고 있습니다. 단순 View를 반환하고자 하면 @Controller 어노테이션을 사용하는 것은 어떨까요?

2023-10-18 12:17 UTC, minju412 commented on build.gradle
앗 그렇네요..! 🤭 제거했습니다!

2023-10-18 14:08 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/domain/member/model/Member.java
> +	private String providerId;
`NIT`: 해당 정보들은 따로 묶는것도 좋을 것 같습니다!
```suggestion
	@Enumerated(EnumType.STRING)
	private OAuthInfo oAuthInfo;
	
public class OAuthInfo {
    private OAuth2Provider provider;
    private String providerId;
}
```

2023-10-18 14:08 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/domain/member/repository/MemberRepository.java
> +	Optional<Member> findByProviderId(String providerId);
음.. 아래의 `findByProviderId()`와 같은 기능을 할 것 같은데 조금 위험해 보이네요.
providerId 동일한 케이스는 정말 희박하겠지만 그래도 `OAuth2Provider` 까지 비교하는 방어적인 코드를 짜는게 좋다고 생각해요!

2023-10-20 04:30 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/auth/oauth/api/LoginController.java
습관적으로 `@RestController`를 사용했던 것 같은데, 맞는 말이네요! 현재 코드에서 LoginController가 제거되어서 적용할 수는 없지만 유의하겠습니다.

2023-10-20 06:27 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/member/repository/MemberRepository.java
> +	Optional<Member> findByProviderId(String providerId);
맞습니다! `findByProviderId` 메서드는 코드 내부에서 사용되고 있지 않던 메서드라 제거했습니다!

2023-10-20 06:30 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/member/model/Member.java
> +	private String providerId;
좋습니다!! 해당 코멘트에서 인사이트를 얻어서 복합키를 적용해 보았는데요, `provider`와 `providerId`를 묶어 사용자를 식별하는데 사용합니다. 좋은 리뷰 감사합니다! 👍

2023-10-20 06:37 UTC, minju412 commented on build.gradle
> -jacocoTestCoverageVerification {
앗 jacoco 관련 코드는 건든 적이 없는 것 같은데 왜 제거되었는지 모르겠네요..🥲 다시 추가해 놓겠습니다!

2023-10-20 07:19 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/auth/oauth/CustomOauth2UserService.java
1. 말씀하신대로 Optional을 이용하여 isEmpty일 경우 최초 로그인한 사용자겠네요..! isFirst 변수 삭제했습니다!
2. 요것도 불필요한 로직이라고 생각되어 제거했습니다.
3. 클린 코드에 대한 아이디어 너무 감사합니다! 한 가지 역할만 하도록 분리했는데, 코드로 확인 부탁드립니다! 👍

2023-10-20 11:28 UTC, Nine-JH approved these changes

2023-10-20 11:28 UTC, Jeonwoojae approved these changes

2023-10-20 11:28 UTC, Jeonwoojae commented on src/main/java/com/petitapetit/miml/domain/auth/oauth/CustomOauth2UserService.java
> +			memberRepository.save(member);
해당 부분에서 단순히 db에 저장된 내용을 가져와서 다시 저장하고 있습니다
업데이트 부분이 주석 되어있는데 의도한 것인가요?🤔

2023-10-20 11:28 UTC, Jeonwoojae commented on src/main/java/com/petitapetit/miml/domain/member/repository/MemberRepository.java
> +@Transactional
`@Transactional`은 보통 서비스 레이어에서 많이 사용하는데 레포지토리에서 사용하시게 된 이유가 궁금합니다!

2023-10-20 11:28 UTC, kdmstj approved these changes

2023-10-20 13:23 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/auth/oauth/CustomOauth2UserService.java
> +			memberRepository.save(member);
해당 로직은 불필요한 로직이라고 판단되어 삭제했습니다!

2023-10-20 13:28 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/member/repository/MemberRepository.java
> +@Transactional
습관적으로 사용했던 것 같은데, 고민해보니 레포지토리에서는 트랜잭션을 사용할 필요가 없을 것 같네요..! 제거하겠습니다! 👍

2023-10-20 13:34 UTC, merged