Feature/issue#13 플레이리스트 등록, 수정, 조회, 삭제 기능 구현
petit-a-petit/MIML pull request #43
Opened 2023-10-25 06:35 UTC by kdmstj

### ✍️ Description
- 플레이리스트 등록, 수정, 조회(플레이리스트 상세 조회, 목록 조회), 삭제 기능을 구현하였습니다. 

<br>

### 🎯 Key Changes
- DTO <-> Entity 를 매핑하는 MapStruct 라이브러리를 사용하였습니다. 
   - 기존에는 엔티티 그대로 Controller에게 반환하였지만, 이에 대해서 필요하지 않은 정보까지 제공한다는 점에서 위험 요소가 된다고 판단하여 Service 계층에서 Mapper에게 entity를 dto로 변환한 것을 위임하였습니다. 
   - MapStruct가 생성한 코드는 다음 디렉토리에 있습니다. `build/generated/sources/annotationProcessor/java/main/com/petitapetit/miml/domain/playlist/mapper/`
- `UriComponentsBuilder`를 통해서 자원이 생성되었을 때 URI를 생성해주는 유틸을 만들어 역할을 분리하였습니다.
- `GlobalExceptionHandler` 에서 @RestControllerAdvice 어노테이션을 통해 여러 컨트롤러에 대해 발생하는 예외에 ExceptionHandler가 적용되도록 하였습니다. 

### 💬 To Reviewers
- `PlayListService` 의 `checkAuthorization`과 `checkExistence`에서 발생하는 예외에 대해서 어떤 상태 코드를 줘야 할지에 대해 의견을 여쭤보고 싶습니다. (해당 코드에 작성된 상태코드는 임의로 작성해놓았습니다.)

2023-10-25 08:15 UTC, Nine-JH reviewed
넘모넘모 고생하셨습니다 👍👍👍
여쭤보신거에 대한 저의 생각은 요렇게 입니다.
* checkAuthorization -> 403 Error
* checkExistence -> 404 Error (Not Found는 일관된 데이터를 주기 때문에 캐시가 가능함)

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/domain/playlist/controller/PlayListController.java
> +    }
`NIT` : 요건 단순한 팁인데 단순히 `JSON` + `HttpStatus.OK` 라면 ResponseEntity 를 Wrapping 하지 않으셔도 됩니다. 일관성이 있어 보기 좋네요 😀
```suggestion
    @PatchMapping("/{play_list_id}")
    public PlayListDto.SaveResponse patchPlayList(@PathVariable("play_list_id") Long playListId,
                                                                  @RequestBody PlayListDto.SaveRequest request){

        Long memberId = 1L;//mock
        return playListService.modifyPlayList(playListId, request, memberId);
    }
```

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/domain/playlist/controller/PlayListController.java
> +        return ResponseEntity.created(uri).body(response);
오.. 경로를 이렇게도 담아줄 수 있나보군요. 배워갑니다👍

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +        if(!Objects.equals(playList.getPlayListId(), memberId)){
`playList.getPlayListId()`, `memberId` 와 동등성 비교를 하네요?? 혹시 이유가 있나요?🧐 PlayList에 따로 memberId가 있는것으로 확인했거든요!

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/global/exception/ErrorResponse.java
> +}
해당문제가 언제 발생했는지에 대한 `TimeStamp`도 찍었으면 좋을 것 같아요! 프론트엔드와 협업 당시에 로그 찾는것도 일이었던 경험이 있어서 ㅋㅋㅋ

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/global/exception/GlobalExceptionHandler.java
Application Exception을 분리한게 인상적이네요 👍👍👍👍

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/util/UriUtil.java
> +    public static URI createUri(String defaultUrl, Long resourceId) {
`NIT`: `resourceId`도 좋아보이는데 조금 더 넓은 의미로 `uriVariables` `pathVariable`도 괜찮아 보이네요

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +        PlayList modifiedPlayList = playListRepository.save(playList);
수정의 경우 JPA 에서는 더티 체킹을 수행하기 때문에 따로 `save()` 메서드를 사용하지 않아도 저장이 됩니다 😀 

https://jojoldu.tistory.com/415

2023-10-25 08:15 UTC, Nine-JH commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +    }
클래스 레벨에서 트랜잭션 관리를 해주는 것도 좋아보이네요.
그리고 `getVerifiedPlaylist` 만 `@Transactional` 설정을 하신 이유가 있을까요?

2023-10-25 14:40 UTC, minju412 requested changes
정말 고생하셨습니다! 👍
여쭤봐 주신 것에 대해서는 저도 자현님의 의견에 동의합니다!

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/controller/PlayListController.java
> +    @PatchMapping("/{play_list_id}")
수정 메서드에 대해 PUT 방식 대신 PATCH 방식을 선택하신 기준이 궁금합니다!

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/dto/PlayListDto.java
> +    public static class Response {
`SaveResponse` 처럼 해당 Response도 어떨 때 사용되는 Response인지 이름을 통해 나타내면 좋을 것 같습니다!

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/entity/PlayList.java
> +    private Long memberId;
Member와 PlayList의 관계가 N:1 일것으로 생각되는데, 연관관계를 설정하지 않으신 이유가 있을까요?!

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +            playList.setIsPublic(request.getIsPublic());
setter 대신 캡슐화를 적용하여 메시지(`playList.updateIsPublic(request.getIsPublic());`)를 통해 객체의 상태를 변경하면 더욱 객체지향적인 설계가 될 것 같아요!

```java
public class PlayList {
    ...
    public void updateIsPublic(Boolean isPublic) {
    this.isPublic = isPublic;
    }
}
```

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +            playList.setName(request.getName());
위와 마찬가지입니다!

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +        Optional<PlayList> optional = playListRepository.findById(PlayListId);
중요한건 아니지만, 86, 87번 라인을 합쳐 아래처럼 사용할 수 있을 것 같습니다! 
`return playListRepository.findById(PlayListId).orElseThrow(()-> new RestApiException(CommonErrorCode.RESOURCE_NOT_FOUND));`

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/global/exception/ErrorCode.java
> +    String name();
`ErrorCode`에 `name`에는 예를 들어 어떤 값이 담길까요..?!

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/util/UriUtil.java
> +public class UriUtil {
우재님께서 알려주신건데, lombok의 `@UtilityClass` 어노테이션에 대해 알아보셔도 좋을 것 같습니다!

2023-10-25 14:40 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/entity/PlayList.java
> +    private Long memberId;
앗 지금 생각해보니 mock 데이터를 담기 위해서일까요..??

2023-10-26 12:52 UTC, Jeonwoojae reviewed
고생하셨습니다👍
Mapper를 잘 몰라서 보고 배울 수 있도록 하겠습니다✍

2023-10-26 12:52 UTC, Jeonwoojae commented on src/main/java/com/petitapetit/miml/global/exception/RestApiException.java
> +public class RestApiException extends RuntimeException{
예외 사항을 커스텀 하는건 매우 좋습니다!👍
하지만 현재 사용하고 있는 부분이 RestApiException 보다는 내부 로직에서 발생하는 예외라 다른 이름이면 이해하기 편할 것 같습니다!
팀에서 회의를 통해 예외를 어떻게 처리할지 전략을 정하면 좋을 것 같네요😁

2023-10-27 03:25 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/playlist/controller/PlayListController.java
> +    }
넵 참고하도록 하겠습니다 :)

2023-10-27 03:26 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +        if(!Objects.equals(playList.getPlayListId(), memberId)){
memberId를 비교해야 하는 데 잘못 작성한 부분이 있었네요!!
캐치해주셔서 감사합니다 :)

2023-10-27 03:27 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/global/exception/ErrorResponse.java
> +}
해당부분에 대해 너무 공감합니다!!ㅎㅎ 추가하도록 하겠습니다~!

2023-10-27 03:32 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/util/UriUtil.java
> +    public static URI createUri(String defaultUrl, Long resourceId) {
넵 추후에 사용할 것을 고려하여 uriVariables로 수정하도록 하겠습니다 !!

2023-10-27 03:36 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/playlist/entity/PlayList.java
> +    private Long memberId;
넵 맞습니다! 빠른 개발을 위해서 User와 아직 연관관계를 설정해두지 않았습니다!

2023-10-27 03:51 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/playlist/controller/PlayListController.java
> +    @PatchMapping("/{play_list_id}")
1. PUT의 메서드의 규약을 따르기 위해서는 존재하지 않는 플레이리스트에 대해 수정을 요청한 경우 새로운 플레이리스트를 추가해주어야 합니다. 하지만, 개발 요구사항에 의해 존재하는 플레이리스트를 수정해야 하기 때문에 PATCH가 더 적절하였습니다.
2. 수정하고 싶은 데이터(플레이리스트 이름, 공개 여부)에 대해 부분적으로 수정하는 요구사항에 따라 대상 리소스를 나타내는 데이터를 대체하는 PUT 메서드보다 부분적인 수정을 하는 PATCH 메서드가 더 적합하다고 판단하였습니다.

2023-10-27 03:56 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +            playList.setIsPublic(request.getIsPublic());
넵!! 저도 동의합니다ㅎㅎ

2023-10-27 04:08 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/global/exception/RestApiException.java
> +public class RestApiException extends RuntimeException{
넵 좋습니다!!

2023-10-27 04:48 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/global/exception/ErrorCode.java
> +    String name();
ErrorCode의 name에는 에러 이름을 담으며, (ex. RESOURCE_NOT_FOUND)
ErrorResponse 의 body 생성 시 ErrorCode.name() 메소드를 통해 에러 이름을 담는데 사용됩니다.
```
CommonErrorCode.java

RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "Resource not exists");
```
ErrorCode 인터페이스를 구현한 CommonErrorCode 열거형에서는 name() 메소드로 열거 객체의 문자열을 리턴합니다.
열거 상수는 에러 이름으로 선언하였기 때문에 객체로 생성 후 문자열을 리턴하게 되면, 에러 이름이 반환됩니다.

2023-10-30 06:49 UTC, kdmstj commented on src/main/java/com/petitapetit/miml/domain/playlist/service/PlayListService.java
> +    }
넵 말씀하신대로 클래스 레벨에서 트랜잭션 관리를 해주는 것이 좋다고 판단하여 코드 변경하였습니다!

2023-10-30 10:37 UTC, minju412 commented on src/main/java/com/petitapetit/miml/domain/playlist/controller/PlayListController.java
> +    @PatchMapping("/{play_list_id}")
혹시 1번의 경우 존재하지 않는 플레이리스트에 대해 수정을 요청한다면 예외 상황으로 처리하는 것에 대해서는 어떻게 생각하시나요?!

2023-10-30 10:41 UTC, minju412 reviewed
코멘트가 꼼꼼하게 반영된 것 같습니다!! 고생하셨습니다!! 😊

2023-10-30 10:41 UTC, minju412 approved these changes

2023-10-31 05:25 UTC, Nine-JH approved these changes

2023-11-01 10:19 UTC, merged